USE PRACTICE;

SELECT * FROM `EMPLOYEE`;

SELECT * FROM `BRANCH`;
DESCRIBE BRANCH;

SELECT EMPLOYEE.`EMPLOYEE_ID`,EMPLOYEE.`EMPLOYEE_NAME`,EMPLOYEE.`JOB_DESCRIPTION`,BRANCH.`BRANCH_NAME`
FROM EMPLOYEE INNER JOIN `BRANCH` ON EMPLOYEE.BRANCH_ID  = BRANCH.`BRANCH_ID`;
/*
🔥 1. INNER JOIN (Most Important)

👉 Returns only matching records
*/

SELECT EMPLOYEE.`EMPLOYEE_ID`,EMPLOYEE.`EMPLOYEE_NAME`,EMPLOYEE.`JOB_DESCRIPTION`,BRANCH.`BRANCH_NAME`
FROM EMPLOYEE LEFT JOIN `BRANCH` ON EMPLOYEE.BRANCH_ID  = BRANCH.`BRANCH_ID`;
/*
🔥 2. LEFT JOIN
👉 Returns ALL records from left table + matching from right
*/

SELECT EMPLOYEE.`EMPLOYEE_ID`,EMPLOYEE.`EMPLOYEE_NAME`,EMPLOYEE.`JOB_DESCRIPTION`,BRANCH.`BRANCH_NAME`
FROM EMPLOYEE RIGHT JOIN `BRANCH` ON EMPLOYEE.BRANCH_ID  = BRANCH.`BRANCH_ID`;
/*
🔥 3. RIGHT JOIN
👉 Returns ALL records from right table
*/


SELECT EMPLOYEE.`EMPLOYEE_ID`,EMPLOYEE.`EMPLOYEE_NAME`,EMPLOYEE.`JOB_DESCRIPTION`,BRANCH.`BRANCH_NAME`
FROM EMPLOYEE FULL JOIN `BRANCH` ON EMPLOYEE.BRANCH_ID  = BRANCH.`BRANCH_ID`;

/*
🔥 4. FULL JOIN (Less used)
👉 Returns everything from both tables
*/
DESCRIBE EMPLOYEE;