USE PRACTICE;


-- 🔟 Show departments with no employees

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM DEPARTMENT D
LEFT JOIN EMPLOYEE E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE E.DEPARTMENT_ID IS NULL;
