USE PRACTICE

-- USE PRACTICE DATABASE 


CREATE TABLE EMPLOYEE (
    ID INT  PRIMARY KEY,
    NAME VARCHAR(20),
    JOB_DESCRIPTION VARCHAR(30),
    SALARY INT
    
);
-- THIS IS HOW WE CREATE A TABLE 

SELECT * FROM `EMPLOYEE`

UPDATE `EMPLOYEE`
SET JOB_DESCRIPTION = "SOFTWARE ENGINEER"
WHERE  JOB_DESCRIPTION  = "THAYUB";

-- THIS IS HOW WE UPDATE THE DATA USING SET KEYWORD ;



DELETE FROM `EMPLOYEE` 
WHERE ID = 10;

--  THIS IS HOW WE DELETE THE TABLE;



UPDATE  `EMPLOYEE` 
SET NAME = "MOHIDEEN THAYUB" 
WHERE  NAME =  "THAYUB";

DELETE FROM  `EMPLOYEE` 
WHERE  `ID` = 1;

INSERT INTO `EMPLOYEE` VALUES (
    1,"MOHIDEEN THAYUB","SOFTWARE ENGINEER",100000
);

-- THIS IS HOW WE INSERT THE VALUE INTO TABLE 
 
SELECT * FROM EMPLOYEE ;

-- THIS IS HOW WE READ THE TABLE 