USE PRACTICE;

-- ADDING A COLUMN FOR  HIRE_DATA;
ALTER TABLE `EMPLOYEE`  ADD COLUMN  HIRE_DATE DATE;

UPDATE `EMPLOYEE` SET `HIRE_DATE` =  "2026-01-15";


UPDATE `EMPLOYEE`
SET `HIRE_DATE`  = "2005-07-01"
WHERE `HIRE_DATE` = "2026-01-15";
-- WE UPDATE THE TABLE  USING UPDATE CLAUSE;

UPDATE `EMPLOYEE` 
SET  `HIRE_DATE` = "2026-01-01"
WHERE `JOB_DESCRIPTION` = "SOFTWARE ENGINEER"; 
-- UPDATE THE DATE FOR SPECIFIC ROLE  


UPDATE `EMPLOYEE`
SET  `HIRE_DATE`  = "2025-12-01"
WHERE `JOB_DESCRIPTION`= "UI UX DESIGNER";

UPDATE `EMPLOYEE` SET `HIRE_DATE` = "2025-11-01" WHERE  `JOB_DESCRIPTION` IN ("CYBER SECUIRTY ENGINEER", "PENTESTING ENGINEER");
-- WE MODIFT THE DATA USING IN KEYWORD 



SELECT NOW();
--  TO SHOW CURRENT DATE AND TIME 

SELECT CURDATE();
-- TO SHOW CURRENT DATE ONLY

SELECT DATE_FORMAT(CURDATE(), "%D/%M/%Y") DATE ;
-- TO SHOW DATE ACCORDING BY MY WISH 
SELECT  DATEDIFF(CURDATE(), "2024-12-01") DATE ;
-- TO SHOW HOW TO MANY DAY BETWEEN CURRENT AND GIVEN DATE;

SELECT  DATE_ADD(CURDATE(),INTERVAL  10 DAY)   "AFTER ONE YEAR";
-- TO KNOW WHAT WILL BE THE DATE AFTER  THIS DAY WHICH I MENTIONED  AFTER INTERVAL;

-- THIS IS GOING TO BE  A EXERCISE SECTION

SELECT CURDATE() 'START DATE',
DATE_ADD(CURDATE(), INTERVAL 1 DAY ) 1_DAY_LATER,
DATE_ADD(CURDATE() , INTERVAL 1 WEEK ) 1_WEEK_LATER,
DATE_ADD(CURDATE(), INTERVAL 1 MONTH) 1_MONTH_LATER,
DATE_ADD(CURDATE() ,INTERVAL 6 MONTH) 1_HALF_YEAR_LATER,
DATE_ADD(CURDATE(),INTERVAL 1 YEAR) 1_YEAR_LATER;

-- THIS EXERCISE WAS GIVEN BY LOGIC FIRST  CHANNEL;

SELECT * FROM EMPLOYEE;


