
USE PRACTICE;

/*
🔹 What is a Foreign Key?
👉 Simple definition:

A Foreign Key is a column (or group of columns) in one table that refers to the PRIMARY KEY of another table.

📌 It is used to connect two tables and maintain data integrity.

*/
CREATE TABLE DEPARTMENT(
    DEPARTMENT_ID  INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(50) 
);

CREATE TABLE EMPLOYEE(
    ID INT  PRIMARY KEY,
    NAME VARCHAR(50),
    DEPARTMENT_ID INT,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (DEPARTMENT_ID) -- THIS LINE  REFERS THE DEPARTMENT TABLE 
);
/*
I HAD A QUESTION  WHILE LEARNING ABOUT FOREIGN KEYS WHY THERE ARE TWO DEPARTMENT_ID'S.THE FIRST DEPARTMENT_ID IS BELONGS TO THE EMPLOYEE TABLE 
AND THE SECOND ONE IS  REFRENCES THAT REFERS THE PARENT DEPARTMENT_ID;

QUESTION:

CAN I DELETE THE DEPARTMENT TABLE ? 
I CAN'T DELETE THE DEPARTMENT  TABLE BECAUSE EMPLOYEE TABLE REFER THE DEPARTMENT TABLE WITH FORIEGN KEY SO I
CAN'T DELETE THE DEPARTMENT TABLE . IF I HAVE TO DELETE THE DEPARTMENT FIRST I SHOULD DELETE THE EMPLOYEE TABLE THEN I CAN DELETE
THE DEPARTMENT TABLE OTHERWISE I SHOULD CUT THE LINK BETWEEN TWO TABLE  AFTER DONE THAT I CAN DELETE THE DEPARTMENT TABLE EASILY;

✨ Polished interview-ready version (recommended)

I cannot delete the DEPARTMENT table directly because the EMPLOYEE table references it using a foreign key. To delete the DEPARTMENT table, I must either drop the EMPLOYEE table first or remove the foreign key constraint between the two tables. Once the relationship is removed, the DEPARTMENT table can be deleted safely.

This sounds clear, confident, and professional.
*/

INSERT INTO `EMPLOYEE` VALUES (
   2,"MOHAMED SIDDIQ",4
);
INSERT INTO `DEPARTMENT` VALUES (
    4,"SECURITY"
);
SELECT  * FROM `DEPARTMENT`;

SELECT  * FROM `EMPLOYEE`;



/*
INSERT INTO EMPLOYEE (ID, NAME, JOB_DESCRIPTION, SALARY, DEPARTMENT_ID, HIRE_DATE) VALUES
(1, 'Arun',   'SOFTWARE ENGINEER', 55000, 1, '2021-06-15'),
(2, 'Bala',   'QA ENGINEER',       42000, 2, '2020-03-10'),
(3, 'Charan', 'UI UX DESIGNER',    48000, 3, '2022-01-25'),
(4, 'Divya',  'SOFTWARE ENGINEER', 60000, 1, '2019-11-05'),
(5, 'Ezhil',  'QA ENGINEER',       40000, 2, '2023-04-18'),
(6, 'Farah',  'PRODUCT MANAGER',   75000, 4, '2018-08-12'),
(7, 'Ganesh', 'DEVOPS ENGINEER',   68000, 5, '2021-09-30'),
(8, 'Hari',   'DATA ANALYST',      52000, 6, '2022-12-01'),
(9, 'Isha',   'CYBER SECURITY ENGINEER', 70000, 7, '2020-07-20'),
(10,'Jeeva',  'INTERN',            25000, 1, '2024-02-05');

*/


-- THERE IS A EXERCISE TO DO 
