USE PRACTICE; 

-- THIS IS VIDEO ABOUT TO LEARN FUNCTIONS

-- TO COUNT HOW MANY EMPLOYEES IN THE TABLE  WE USE (COUNT) FUNCTION 
-- TOTAL IS USE TO SHOW THE OUTPUT 
SELECT  COUNT(*) FROM `EMPLOYEE`;
-- OR 
SELECT  COUNT(*) TOTAL FROM `EMPLOYEE`;


-- COUNT  FUNCTION INSIDE WHERE CLASS;
SELECT COUNT(*) SOFTWARE_ENGINEERS_COUNTS FROM `EMPLOYEE`
WHERE `JOB_DESCRIPTION` = "SOFTWARE ENGINEER";

SELECT * FROM `EMPLOYEE`;