USE PRACTICE; 

-- THIS IS VIDEO ABOUT TO LEARN FUNCTIONS

-- TO COUNT HOW MANY EMPLOYEES IN THE TABLE  WE USE (COUNT) FUNCTION 
-- TOTAL IS USE TO SHOW THE OUTPUT 
SELECT  COUNT(*) FROM `EMPLOYEE`;
-- OR 
SELECT  COUNT(*) TOTAL FROM `EMPLOYEE`;

-- I UPDATED THE SALARY USING UPDATE CLAUSE 
UPDATE   `EMPLOYEE` 
SET  `SALARY` = 100000
WHERE `SALARY`  = 45000;



/*
THE MOST AGGREGATE FUNCTIONS IN MATH

COUNT(*);
AGE();
SUM()
MAX();
MIN();

*/
-- COUNT  FUNCTION INSIDE WHERE CLASS;
SELECT COUNT(*) FROM `EMPLOYEE`
WHERE `JOB_DESCRIPTION` = "SOFTWARE ENGINEER";

-- TO CALCULATE AVERAGE SALARY USING AVG() FUNCTION 
SELECT AVG(`SALARY`) FROM `EMPLOYEE`;

-- TO SUM THE SALARY USING SUM() FUNCTION 
SELECT  SUM(`SALARY`) FROM `EMPLOYEE`
WHERE `JOB_DESCRIPTION` = "SOFTWARE ENGINEER";


SELECT MAX(`SALARY`) FROM `EMPLOYEE`;

SELECT MIN(`SALARY`) FROM `EMPLOYEE`;
SELECT * FROM `EMPLOYEE`;