USE PRACTICE; 

-- THIS IS VIDEO ABOUT TO LEARN FUNCTIONS

-- TO COUNT HOW MANY EMPLOYEES IN THE TABLE  WE USE (COUNT) FUNCTION 
-- TOTAL IS USE TO SHOW THE OUTPUT 
SELECT  COUNT(*) FROM `EMPLOYEE`;
-- OR 
SELECT  COUNT(*) TOTAL FROM `EMPLOYEE`;

-- I UPDATED THE SALARY USING UPDATE CLAUSE 
UPDATE   `EMPLOYEE` 
SET  `SALARY` = 100000
WHERE `SALARY`  = 45000;



/*
THE MOST AGGREGATE FUNCTIONS IN MATH

COUNT(*);
AVG();
SUM()
MAX();
MIN();

*/
-- COUNT  FUNCTION INSIDE WHERE CLASS;
SELECT COUNT(*) FROM `EMPLOYEE`
WHERE `JOB_DESCRIPTION` = "SOFTWARE ENGINEER";

-- TO CALCULATE AVERAGE SALARY USING AVG() FUNCTION 
SELECT AVG(`SALARY`) FROM `EMPLOYEE`;

-- TO SUM THE SALARY USING SUM() FUNCTION 
SELECT  SUM(`SALARY`) FROM `EMPLOYEE`
WHERE `JOB_DESCRIPTION` = "SOFTWARE ENGINEER";
-- TO CALCULATE THE MAXIMUM SALARY 
SELECT MAX(`SALARY`) FROM `EMPLOYEE`;
-- TO CALCULATE MINIMUM SALARY;
SELECT MIN(`SALARY`) FROM `EMPLOYEE`;

<<<<<<< HEAD

=======
 
>>>>>>> 1db7214 (i learnt string functions and done a exercise)
-- STRING AGREGATE FUNCTIONS 

-- UCASE() IS TO CONVERT THE STRING TO UPPERCASE;
SELECT UCASE(`NAME`) FROM EMPLOYEE;

-- LCASE() IS TO CONVERT THE STRING TO LOWERCASE;
SELECT LCASE(`NAME`) FROM EMPLOYEE;

-- TO  COUNT  HOW MANY CHARACTER IN THE STRING ;
SELECT NAME ,CHAR_LENGTH(NAME) FROM `EMPLOYEE`;


-- TO CONCATINATE TWO STRING 
SELECT  NAME ,CONCAT("RS.",`SALARY`) FROM `EMPLOYEE`;


-- TO SHOW THE DATA READABLE WAY 
SELECT  NAME, CONCAT("RS.",FORMAT(`SALARY`,1)) `SALARY` FROM `EMPLOYEE`;

/*
Interview-ready explanation 🎯

This query is used to format numeric salary values into a readable currency format using FORMAT() and CONCAT().
*/

/* What does LEFT() do? 🧠
LEFT() extracts characters from the LEFT (start) of a string.
*/
SELECT NAME  , LEFT(`JOB_DESCRIPTION`,5) FROM `EMPLOYEE`;

<<<<<<< HEAD
=======

>>>>>>> 1db7214 (i learnt string functions and done a exercise)
/*
Interview one-liner 🎯

LEFT() is used to extract a fixed number of characters from the beginning of a string.
<<<<<<< HEAD

*/
=======
*/

>>>>>>> 1db7214 (i learnt string functions and done a exercise)
SELECT * FROM `EMPLOYEE`;