USE PRACTICE;

DESCRIBE `EMPLOYEE`;
-- TO KNOW THE INFORMATION ABOUT EMPLOYEE TABLE;


/*
🔹 What is GROUP BY in SQL?

👉 Simple definition:

GROUP BY groups rows that have the same value and allows you to apply aggregate functions on each group.

📌 You cannot use aggregate functions meaningfully without GROUP BY.

*/
/*
🔹 What is HAVING clause?
👉 Simple definition:

HAVING is used to filter groups,
just like WHERE filters rows.

*/
SELECT JOB_DESCRIPTION , AVG(SALARY) FROM `EMPLOYEE`  GROUP BY `JOB_DESCRIPTION`;
-- TO FIND THE AVG SALARY OF  EACH JOB DESCRIPTION  BY GROUP BY FUNCTION

SELECT  `JOB_DESCRIPTION` ,COUNT(ID) FROM `EMPLOYEE` GROUP BY  `JOB_DESCRIPTION`;
-- TO COUNT HOW MANY EMPLOYEE IS WORKING  IN  EACH CATEGORY;
SELECT  JOB_DESCRIPTION , SUM(SALARY) FROM `EMPLOYEE` GROUP BY `JOB_DESCRIPTION`;
-- TO SUM THE EMPLOYEE SALARY 


SELECT JOB_DESCRIPTION,`NAME` FROM `EMPLOYEE`;
-- IF YOU GROUP BY WITHOUT ANY AGREGRATE FUNCTION . THAT OUTPUY WILL NOT BE MEANINGFUL.

SELECT `JOB_DESCRIPTION`, COUNT(ID) FROM `EMPLOYEE`GROUP BY `JOB_DESCRIPTION` HAVING  COUNT(`ID`) > 1;
-- TO FILTER GROUP  BY HAVING CLAUSE . IF THE GROUP COUNT IS GREATER THAN 2;

SELECT * FROM `EMPLOYEE` WHERE `SALARY`  > 30000 AND  `SALARY` <= 100000;
-- LET REVISE THE WHERE CLAUSE WHILE LEARNING GROUP BY AND HAVING ;

SELECT `JOB_DESCRIPTION` ,COUNT(`ID`) FROM `EMPLOYEE` GROUP BY `JOB_DESCRIPTION` HAVING  COUNT(`ID`) > 1 ORDER BY `JOB_DESCRIPTION`;
-- WE CALCULATE HOW MANY EMPLOYEE WORKING IN EACH  CATEGORY THEN  WE SORT IT ALPHABATICALLY WITH ORDER BY CLAUSE; 

SELECT `JOB_DESCRIPTION` ,COUNT(ID) FROM `EMPLOYEE` WHERE  `SALARY` >  50000 GROUP BY `JOB_DESCRIPTION` HAVING COUNT(`ID`) > 1 ORDER BY  `JOB_DESCRIPTION`;
-- TO FILTER OUT IF THE SALARY IS   GREATER THAN  50000 AND THE COUNT SHOULD BE GREATER THAN 1. 
 SELECT * FROM `EMPLOYEE`;
