
USE PRACTICE;
/*
What is orderBy ? 
ORDER BY is an SQL clause used to sort the result set in a specific order.
*/

-- THIS IS HOW WE USE ORDER BY FOR TWO VALUES;
SELECT  `NAME`,`SALARY` FROM `EMPLOYEE`
ORDER BY NAME ASC , SALARY ASC;  -- SORT THE SALARY BY DESCENDING ORDER ;

-- DESC IS A KEYWORD TO SORT THE SALARY DESCENDING ORDER;
SELECT SALARY FROM `EMPLOYEE`
ORDER BY `SALARY` DESC ;


-- TO SHOW ALL VALUES 
SELECT  * FROM `EMPLOYEE`
ORDER BY `NAME`;

-- WHERE INSIDE ORDER BY WITH SPECIFIC CONDITION 
SELECT * FROM `EMPLOYEE`
WHERE `JOB_DESCRIPTION` = "SOFTWARE ENGINEER"
ORDER BY `JOB_DESCRIPTION`;

-- ASC IS  A KEYWORD TO SORT THE SALARY ACSENDING ORDER; 
SELECT `SALARY` FROM EMPLOYEE
ORDER BY `SALARY` ASC ;


-- ORDER BY with WHERE 🔍
SELECT * FROM `EMPLOYEE`
WHERE `SALARY` <  50000
ORDER BY `SALARY`;


/*
Interview one-liner 🎯

ORDER BY is used to sort query results in ascending or descending order.
*/

SELECT  * FROM `EMPLOYEE`;

INSERT INTO EMPLOYEE VALUES 
(10,"MOHAMED","PENTESTING ENGINEER",200000);

DESCRIBE EMPLOYEE;