
USE PRACTICE;
/*
What is orderBy ? 
ORDER BY is an SQL clause used to sort the result set in a specific order.
*/

-- THIS IS HOW WE USE ORDER BY FOR TWO VALUES;
SELECT  `NAME`,`SALARY` FROM `EMPLOYEE`
ORDER BY NAME ASC , SALARY ASC;  -- SORT THE SALARY AND NAME BY ASCENDING ORDER ;

-- DESC IS A KEYWORD TO SORT THE SALARY DESCENDING ORDER;
SELECT SALARY FROM `EMPLOYEE`
ORDER BY `SALARY` DESC ;


-- TO SHOW ALL VALUES 
SELECT  * FROM `EMPLOYEE`
ORDER BY `NAME`;

-- WHERE INSIDE ORDER BY WITH SPECIFIC CONDITION 
SELECT * FROM `EMPLOYEE`
WHERE `JOB_DESCRIPTION` = "SOFTWARE ENGINEER"
ORDER BY `JOB_DESCRIPTION`;

-- ASC IS  A KEYWORD TO SORT THE SALARY ACSENDING ORDER; 
SELECT `SALARY` FROM EMPLOYEE
ORDER BY `SALARY` ASC ;


-- ORDER BY with WHERE 🔍
SELECT * FROM `EMPLOYEE`
WHERE `SALARY` <  50000
ORDER BY `SALARY`;


/*

-Interviewq one-liner 🎯
-ORDER BY is used to sort query results in ascending or descending order.
*/

SELECT  * FROM `EMPLOYEE`;

-- INSERTING VALUE INTO EMPLOYEE TABLE
INSERT INTO EMPLOYEE VALUES 
(10,"MOHAMED","PENTESTING ENGINEER",200000);

SELECT * FROM  `EMPLOYEE` 
ORDER BY 
    CASE  `JOB_DESCRIPTION`
    WHEN  'SOFTWARE ENGINEER' THEN  1
    WHEN  'UI UX ENGINEER' THEN 2
    WHEN  'QA ENGINEER' THEN 3
    ELSE  4

    END;

/*
🔟 Interview-ready answer 🎯

Custom ORDER BY is used to sort data based on business priority using CASE expressions.
*/
DESCRIBE EMPLOYEE;