USE PRACTICE;


SELECT * FROM `EMPLOYEE`;
-- group by clause is used to group the result set based on one or more columns;

SELECT JOB_DESCRIPTION, COUNT(*) EMPLOYEE_COUNT FROM `EMPLOYEE` GROUP BY `JOB_DESCRIPTION`;


SELECT JOB_DESCRIPTION,AVG(SALARY) TOTAL_SALARY FROM `EMPLOYEE` GROUP BY `JOB_DESCRIPTION`;

 -- HAVING CLAUSE  


-- having clause is used to filter the group based on some condition;

SELECT JOB_DESCRIPTION,SUM(SALARY) FROM `EMPLOYEE` GROUP BY `JOB_DESCRIPTION` HAVING SUM(`SALARY`) > 100000;

-- CALCULATE WHICH JOB ROLE SALARY IS GREATER THAN 100000 ;

SELECT  JOB_DESCRIPTION ,AVG(SALARY) FROM `EMPLOYEE` GROUP BY `JOB_DESCRIPTION` HAVING AVG(`SALARY`) > 50000;

-- TO CALCULATE ROLE WHICH AVERAGE SALARY IS GREATER THAN 50000;

SELECT  JOB_DESCRIPTION, COUNT(*) FROM `EMPLOYEE`  GROUP BY `JOB_DESCRIPTION` HAVING  COUNT(*) > 1 ;

-- TO CALCULATE WHICH JOB ROLE HAS MORE THAN 1 EMPLOYEE;

SELECT * FROM `EMPLOYEE`;
