USE PRACTICE;

-- HERE WE ARE GOING TO LEARN DATE FUNCTIONS
SELECT * FROM `EMPLOYEE`;
ALTER TABLE `EMPLOYEE` ADD COLUMN HIRE_DATE DATE;
--  ADDING HIRE DATA COLUMN IN  EMPLOYEE TABLE;

SELECT * FROM `EMPLOYEE`;

SELECT NOW();
-- GET THE  CURRENT DATE AND TIME
SELECT CURDATE(); 
SELECT  DATE(NOW());
-- GET THE CURRENT DATE AND BOTH ARE USED TO DO THE SAME THING;

SELECT  DATE_FORMAT(CURDATE(), "%D/%M/%Y") AS  FORMAT_DATE; 
-- HERE USE  FORMAT FUNCTION  TO FORMATTING THE DATE;  

SELECT DATEDIFF(CURDATE(), "2022/01/01") AS  BETWEEN_DAYS;
-- FIND THE DAYS BETWEEN TWO DATES;

SELECT DATE_ADD(CURDATE(),INTERVAL 1 WEEK) AFTER_ONE_YEAR;
-- FIND THE DATE AFTER THIS INTERVAL DATE;

-- exercise 

SELECT CURDATE() 'START DATE',
 DATE_ADD(CURDATE(),INTERVAL 1 DAY) AS  ONE_DAY_LATER,
 DATE_ADD(CURDATE(),INTERVAL 1 WEEK) AS  ONE_WEEK_LATER,
 DATE_ADD(CURDATE(),INTERVAL 1 MONTH) AS ONE_MONTH_LATER,
 DATE_ADD(CURDATE(),INTERVAL 1 YEAR) AS ONE_YEAR_LATER

-- 