USE PRACTICE;
DESCRIBE EMPLOYEE;

SELECT * FROM `DEPARTMENT`;

DESCRIBE `DEPARTMENT`;

SHOW TABLES;

SHOW INDEX FROM EMPLOYEE;

CREATE INDEX  NAME_INDEX ON EMPLOYEE(EMPLOYEE_NAME);
-- THIS IS HOW WE ADD INDEX FOR COLUMN
ALTER TABLE `EMPLOYEE` DROP INDEX NAME_INDEX;
-- REMOVE INDEX FROM EMPLOYEE TABLE  

