-- here we are going to learn  about foriegn key 


USE PRACTICE;
ALTER TABLE `DEPARTMENT` ADD COLUMN EMPLOYEE_ID VARCHAR(20);

ALTER TABLE `EMPLOYEE` DROP FOREIGN KEY FK_DEPARTMENT_ID;
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_DEPARTMENT_ID  FOREIGN KEY (`DEPARTMENT_ID`) REFERENCES  `DEPARTMENT` (`DEPARTMENT_ID`);
-- THIS IS HOW WE WILL ADD FOREIGN KEY IN EXISTING TABLE
ALTER TABLE `EMPLOYEE` ADD CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY  (`EMPLOYEE_ID`) REFERENCES  `EMPLOYEE` (`EMPLOYEE_ID`);

CREATE TABLE DEPARTMENT(
    DEPARTMENT_ID  INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(20) NOT NULL
);


CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID INT PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(20),
    DEPARTMENT_ID INT 
    -- FOREIGN KEY  (DEPARTMENT_ID) REFERENCES DEPARTMENT (DEPARTMENT_ID)
);


ALTER TABLE `EMPLOYEE` ADD CONSTRAINT FK_DEPARMENT_ID FOREIGN KEY (`DEPARTMENT_ID`) REFERENCES `DEPARTMENT` (`DEPARTMENT_ID`);
-- THIS IS HOW WE ADD FORIEGN KEY IN EXISTING TABLE;
SHOW TABLES;
INSERT INTO `DEPARTMENT` VALUES
    (1,"ENGINEERING"),
    (2,"MARKETING"),
    (3,"SALES"),
    (4,"DESIGNING"),
    (5,"TALENT ACQUISITION");

INSERT INTO `EMPLOYEE` VALUES
(1,"JOGN",1),
(2,"MOHIDEEN",5),
(3,"MOHAMED",2),
(4,"THAYUB",3),
(5,"AJEES",4);
INSERT INTO `EMPLOYEE` VALUES(
    6,"RAHUL",6
);

DELETE FROM `DEPARTMENT` WHERE `DEPARTMENT_ID` = 6;


SELECT * FROM `EMPLOYEE`;
SELECT * FROM `DEPARTMENT`;

DROP TABLE `DEPARTMENT`;

UPDATE `EMPLOYEE` SET `DEPARTMENT_ID` = 10 WHERE  `EMPLOYEE_ID` = 5;
-- I GET ERROR WHEN I TRY TO  UPDATE THE EMPLOYEE TABLE DEPARTMENT ID USING UPDAT KEYWORD;

/*
👉 “Why not store department name in employee table?”

👉 You should say:

We avoid storing department name in the employee table to prevent data redundancy and maintain data consistency. By using a separate department table and linking it with a foreign key, we ensure that updates happen in one place and avoid duplication of data.
*/