-- here we are going to learn  about foriegn key 


USE PRACTICE;


CREATE TABLE DEPARTMENT(
    DEPARTMENT_ID INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID INT PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(30),
    JOB_DESCRIPTION VARCHAR(30),
    SALARY INT,
    DEPARTMENT_ID INT ,
    CONSTRAINT FK_DEPARTMENT_ID FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);
DESCRIBE EMPLOYEE;

ALTER TABLE `EMPLOYEE` DROP FOREIGN KEY FK_DEPARTMENT_ID;
