USE PRACTICE;
SELECT * FROM `EMPLOYEE`;


INSERT INTO `DEPARTMENT` VALUE
(1,"HR"),
(2,"ENGINEERING"),
(3,"DESIGING"),
(4,"MARKETING"),
(5,"SALES");
DROP TABLE `DEPARTMENT`;

CREATE TABLE DEPARTMENT(
    DEPARTMENT_ID INT,
    DEPARTMENT_NAME INT
);

ALTER TABLE `DEPARTMENT` ADD COLUMN `DEPARTMENT_NAME` VARCHAR(20);


SELECT * FROM `DEPARTMENT`;