USE PRACTICE;

DESCRIBE DEPARTMENT;

-- here we join the employee and department table using inner join .
SELECT  EMPLOYEE.EMPLOYEE_ID ,EMPLOYEE.EMPLOYEE_NAME, EMPLOYEE.JOB_DESCRIPTION,DEPARTMENT.DEPARTMENT_NAME FROM EMPLOYEE 
INNER JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID;


SELECT  EMPLOYEE.EMPLOYEE_ID ,EMPLOYEE.EMPLOYEE_NAME,DEPARTMENT.DEPARTMENT_NAME FROM EMPLOYEE 
LEFT JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID;





SELECT * FROM `EMPLOYEE`;
ALTER TABLE `EMPLOYEE` ADD CONSTRAINT  FK_DEPARTMENT_ID FOREIGN KEY (`DEPARTMENT_ID`) REFERENCES `DEPARTMENT` (`DEPARTMENT_ID`);
DESCRIBE EMPLOYEE;

CREATE TABLE TEST(
    ID INT,
    NAME VARCHAR(20),
    AGE INT

);

