
USE PRACTICE;


CREATE TABLE STUDENT (
    ID INT PRIMARY KEY,
    NAME VARCHAR(30),
    GPA DECIMAL(3,2)
); -- THIS IS HOW WE CREATE TABLE  


INSERT INTO `STUDENT` VALUES 
    (1,"MOHIDEEN THAYUB",2.2),
    (2,"MOHAMED ISMAIL",1.0)
;
-- IF YOU WANT TO INSERT MULTIPLE DATA INTO STUDEN TABLE
 
INSERT INTO `STUDENT` VALUES(
    3,"MOHIDEEN",1.1
); -- TO ADD ONE VALUE INTO TABLE 

SELECT * FROM STUDENT; -- TO SEE WHAT ARE THE VALUES IN THE TABLE;

SHOW TABLES; --  SHOW WHAT ARE THE TABLE EXIST IN THE PRACTICE DATABASE;

DESCRIBE STUDENT; -- WHAT ARE THE COLUMNS ARE AVAILABLE IN THE STUDENT TABLE


ALTER TABLE `STUDENT`  ADD  DEPARTMENT VARCHAR(10); --  ADD NEW COLUMN IN EXISTING TABLE;

ALTER TABLE `STUDENT` DROP  `DEPARTMENT`; -- TO REMOVE DEPARTMENT COLUMN IN STUDEN TABLE;
DROP TABLE `STUDENT`; -- TO DELETE THE TABLE ;