USE PRACTICE;

SELECT * FROM `EMPLOYEE`

/*
🧠 What is GROUP BY?

👉 GROUP BY is used to group rows that have the same values

note : When you use grouppBy you should use aggregate function 
that's when it will be meaningfully ;

*/

SELECT JOB_DESCRIPTION,AVG(SALARY) AS AVERAGE_SALARY FROM `EMPLOYEE`
GROUP BY  `JOB_DESCRIPTION`;
-- HERE WE GROUP JOB ROLE ACCORDING TO THE  JOB DESCRIPTION AND CALCULATE THE AVERAGE SALARY;

SELECT  JOB_DESCRIPTION  AS  JOB_ROLE, COUNT(*) AS EMPLOYEE_COUNT FROM `EMPLOYEE`
GROUP BY `JOB_DESCRIPTION`;
-- HERE WE COUNT HOW MANY EMPLOYEES IN EACH ROLE ;



/*
🧠 What is HAVING?

👉 HAVING is used to filter grouped data

*/
SELECT JOB_DESCRIPTION , COUNT(*) FROM `EMPLOYEE`
GROUP BY `JOB_DESCRIPTION`  
HAVING  COUNT(*) > 1;
-- HERE WE USE HAVING TO FILTER GROUP DATA

SELECT  JOB_DESCRIPTION ,COUNT(*) FROM `EMPLOYEE`
WHERE `SALARY`  > 50000
GROUP BY `JOB_DESCRIPTION`;
