USE PRACTICE;


/*
🧠 What are Constraints in SQL?

👉 Constraints are rules applied to a table’s columns
👉 They control what type of data is allowed
*/

CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMPLOYEE_NAME  VARCHAR(20) ,
    JOB_DESCRIPTION VARCHAR(20) ,
    SALARY INT,
    HIRE_DATE  DATE
);
-- THIS IS HOW WE CREATE TABLE WITH CONSTRAINTS   
SHOW TABLES;
SELECT * FROM `EMPLOYEE`;


-- ADD CONSTRAINTS AFTER CREATE THE TABLE
ALTER TABLE  `EMPLOYEE` MODIFY  EMPLOYEE_NAME  VARCHAR(30) NOT NULL;
ALTER TABLE `EMPLOYEE` ALTER  JOB_DESCRIPTION SET DEFAULT  'UNIASSIGNED';
ALTER TABLE `EMPLOYEE` ADD CONSTRAINT CHECK_SALARY CHECK (SALARY > 10000); -- HERE I HAVE ADDED NAME FOR CONSTRAINT

-- REMOVE CONSTRAINTS AFTER CREATE THE TABLE
ALTER TABLE  `EMPLOYEE` MODIFY `EMPLOYEE_NAME` VARCHAR(30);
ALTER TABLE `EMPLOYEE` ALTER JOB_DESCRIPTION DROP DEFAULT;
ALTER TABLE  `EMPLOYEE` DROP CHECK CHECK_SALARY; 

DESCRIBE EMPLOYEE;