USE PRACTICE;
-- HERE WE ARE GOING TO LEARN  ABOUT  AGGREGATE FUNCTIONS IS SQL 
SELECT * FROM `EMPLOYEE`;

SELECT COUNT(*) TOTAL_EMPLOYEE FROM `EMPLOYEE`;
-- COUNT FUNCTION IS USED TO COUNT THE TOTAL EMPLOYEE IN THE TABLE;

SELECT COUNT(*) FROM `EMPLOYEE` 
WHERE `JOB_DESCRIPTION` = 'Software Eng';
-- where clause inside aggregate function ;

SELECT AVG(SALARY)  AS SOFTWARE_ENGINEER_AVERAGE_SALARY FROM `EMPLOYEE`
WHERE `JOB_DESCRIPTION` = 'Software Eng';

--AVG IS USE TO FIND THE AVERAGE SALARY OF THE SOFTWARE ENGINEER;

SELECT SUM(SALARY) FROM `EMPLOYEE`
WHERE `JOB_DESCRIPTION` = 'Software Eng';
-- CALCULATE TOTAL SALARY OF SOFTWARE ENGINEER SALARY;

SELECT MAX(SALARY) FROM `EMPLOYEE`;
--  FIND THE  MAXIMUM SALARY OF THE EMPLOYEE WE USE MAX FUNCTION  


SELECT MIN(SALARY) FROM `EMPLOYEE`;
--  FIND THE  MINIMUM SALARY OF THE EMPLOYEE WE USE MIN FUNCTION  

-- THESE FIVE FUNCTIONS MOST COMMONLY USE MATH  AGGREGATE FUNCTIONS 
--------------------------------------------------------------------

SELECT UCASE(EMPLOYEE_NAME),SALARY FROM `EMPLOYEE`;
-- UCASE IS USED TO CONVERT UPPERCASE;

SELECT UCASE(EMPLOYEE_NAME),CHAR_LENGTH(EMPLOYEE_NAME) CHAR_COUNT FROM `EMPLOYEE`;
-- CHARACTER COUNT OF THE EMPLOYEE NAME 

SELECT EMPLOYEE_NAME,CONCAT('RS.',SALARY) FROM `EMPLOYEE`;
-- CONCAT FUNCTION IS USED TO ADD STRING
SELECT `EMPLOYEE_NAME`,CONCAT('RS.',FORMAT(SALARY,0)) SALARY FROM `EMPLOYEE`;
-- The FORMAT() function in SQL is used to format a value (like a date, time, or number) with a specified format pattern and optional culture, returning the result as a string


SELECT EMPLOYEE_NAME , LEFT(`JOB_DESCRIPTION`,3) FROM `EMPLOYEE`;
-- IF YOU WANT FIRST THREE CHARACTER IN JOB DESCRIPTION  FOR WE USE LEFT FUNCTION ;
DESCRIBE EMPLOYEE;