USE PRACTICE;
-- GET ALL EMPLOYEE 
SELECT * FROM EMPLOYEE;

SELECT `EMPLOYEE_NAME`,`SALARY` FROM `EMPLOYEE`;
--  SHOW EMPLOYEE NAME AND SALARY 

-- SHOW EMPLOYEE NAME ONLYE
SELECT `EMPLOYEE_NAME` FROM `EMPLOYEE`;

-- SHOW EMPLOYEE WITH SALARY > 50000
SELECT * FROM `EMPLOYEE`
WHERE `SALARY` > 50000;


-- GET EMPLOYEES WITH SALARY < 40000;
SELECT * FROM `EMPLOYEE` WHERE  SALARY <  40000;

-- LEVEL2;
-- GET EMPLOYEES WHOSE ROLE IS Backend Dev
SELECT * FROM `EMPLOYEE`
WHERE `JOB_DESCRIPTION` = 'Backend Dev';

-- GET EMPLOYEES WHOSE NAME STARTS WITH A ;
SELECT * FROM `EMPLOYEE`
WHERE `EMPLOYEE_NAME` LIKE "A%";

--GET EMPLOYEES WHOSE NAME ENDS WITH A;
SELECT * FROM `EMPLOYEE` WHERE `EMPLOYEE_NAME` LIKE "%a";
-- GET EMPLOYEES WHOSE NAME CONTAINS 'VI'

SELECT * FROM `EMPLOYEE`  WHERE `EMPLOYEE_NAME` LIKE "%VI%";
-- SHOW ONLY EMPLOYEE NAME


-- LEVEL 3;
-- SORT THE EMPLOYEE SALARY BY ASCENDING
SELECT * FROM `EMPLOYEE`
ORDER BY `SALARY`;

-- SORT THE EMPLOYEE SALARY BY DESCENDING
SELECT * FROM `EMPLOYEE` ORDER BY `SALARY` DESC;

-- 13️⃣ Show top 3 highest paid employees
SELECT * FROM `EMPLOYEE` ORDER  BY `SALARY` DESC LIMIT 3;

-- SHOW LOWESET TWO SALARIES;
SELECT * FROM `EMPLOYEE` ORDER BY `SALARY` LIMIT 2;


--- LEVEL 4
-- TOTAL SALARY OF THE ALL EMPLOYEES
SELECT SUM(SALARY) AS TOTAL_SALARY FROM `EMPLOYEE`;

-- FIND THE AVERAGE SALARY
SELECT AVG(SALARY) AS AVERAGE_SALARY FROM `EMPLOYEE`;

-- FIND MAXIMUM SALARY  
SELECT MAX(SALARY) AS MAXIMUM_SALARY FROM `EMPLOYEE`;

--FIND THE MINIMUM SALARY 
SELECT MIN(SALARY) AS MINIMUM_SALARY FROM `EMPLOYEE`;

-- FIND THE EMPLOEE COUNT;
SELECT COUNT(*) AS TOTAL_EMPLOYEE FROM `EMPLOYEE`;


-- LEVEL 5
-- COUNT THE EMPLOYEE IN EACH ROLE
SELECT `JOB_DESCRIPTION` ,COUNT(*) AS EMPLOYEE_COUNT FROM `EMPLOYEE`
GROUP BY  `JOB_DESCRIPTION`;


-- FIND THE TOTAL SALARY OF EACH ROLE
SELECT JOB_DESCRIPTION,SUM(SALARY) FROM `EMPLOYEE`
GROUP BY `JOB_DESCRIPTION`;

-- FIND THE AVERAGE SALARY PER ROLE ;
SELECT JOB_DESCRIPTION,AVG(SALARY) FROM `EMPLOYEE`
GROUP BY `JOB_DESCRIPTION`;


-- SHOW ROLES WITH MORE THAN 1 EMPLOYEE 
SELECT COUNT(*), JOB_DESCRIPTION FROM `EMPLOYEE`
GROUP BY `JOB_DESCRIPTION`
HAVING COUNT(*) > 1;

-- SHOW ROLE WHERE AVERAGE SALARY > 60000;
SELECT JOB_DESCRIPTION,AVG(SALARY) FROM `EMPLOYEE`
GROUP BY `JOB_DESCRIPTION` 
HAVING AVG(`SALARY`) > 60000;
