
USE PRACTICE;

-- LEVEL 1
CREATE TABLE EMPLOYEE(
    ID INT PRIMARY KEY,
    NAME VARCHAR(20),
    ROLE VARCHAR(20),
    SALARY INT
); -- HERE WE CREATE THE TABLE ;

SELECT * FROM `EMPLOYEE`;
-- GET ALL EMPLOYEES;


SELECT NAME AS NAME, SALARY AS SALARY FROM EMPLOYEE;
-- NAME AND SALARY OF ALL EMPLOYEE;

SELECT * FROM `EMPLOYEE` WHERE `SALARY` > 50000 ;
-- GET EMPLOYEES WITH SALARY > 50000


SELECT * FROM `EMPLOYEE` 
WHERE NAME  LIKE  "A%";

-- GET EMPLOYEES WHOSE NAME STARTS WITH A;


-- LEVEL 2;

SELECT * FROM `EMPLOYEE`
WHERE `SALARY` >=  40000 AND `SALARY`  <= 70000;
-- GET EMPLOYEES WITH SALARY BETWEEN 40000 AND 70000

SELECT * FROM `EMPLOYEE` 
ORDER BY `SALARY` DESC;
-- SORT EMPLOYEES BY SALARY (HIGHEST FIRST);


SELECT * FROM `EMPLOYEE`
ORDER BY `SALARY` DESC 
LIMIT 3;
-- GET TOP 3 HIGHEST PAID EMPLOYEES;


SELECT * FROM `EMPLOYEE`
WHERE ROLE LIKE  '%DEV%'; 
-- GET EMPLOYEES WHOSE ROLE CONTAINS 'DEV'

-- LEVEL 3
UPDATE  `EMPLOYEE` SET `ROLE` = "PRODUCT MANAGER"
WHERE `ROLE` = 'Product Mgr';
-- UPDATE JOB DESCRIPTION OF A SPECIFIC ROLE 

DELETE FROM `EMPLOYEE` WHERE `SALARY` < 40000
-- DELETE EMPLOYEES WITH `SALARY` LESS THAN 40000;


-- LEVEL 4


SELECT SUM(SALARY) AS TOTAL_SALARY FROM `EMPLOYEE`; `ID`
-- FIND THE TOTAL SALARY OF ALL EMPLOYEE;

SELECT AVG(SALARY) AS AVERAGE_SALARY FROM `EMPLOYEE`;
--FIND AVERAGE SALARY OF ALL EMPLOYEES;

SELECT MAX(SALARY) , MIN(SALARY) FROM EMPLOYEE;
-- FIND THE HIGEST AND LOWEST SALARY  

SELECT COUNT(*) AS TOTAL_EMPLOYEES FROM `EMPLOYEE`;
-- COUNT TOTAL EMPLOYEES 


-- LEVEL 5

SELECT ROLE ,COUNT(*) AS EMPLOYEE_COUNT FROM `EMPLOYEE`
GROUP BY ROLE 
--COUNT EMPLOYEE IN EACH ROLE;

 
SELECT ROLE,SUM(SALARY) AS TOTAL_SALARY FROM `EMPLOYEE` 
GROUP BY `ROLE`;
-- FIND TOTAL SALARY BY ROLE;

SELECT  ROLE,COUNT(*) AS TOTAL_EMPLOYEES FROM `EMPLOYEE`
GROUP BY `ROLE`
HAVING COUNT(*) > 1 ;
-- FIND ROLE WITH MORE THAN 1 EMPLOYEES;


SELECT ROLE, AVG(SALARY) AS AVERAGE_SALARY FROM `EMPLOYEE`
GROUP BY `ROLE`
HAVING AVG(`SALARY`) > 60000;
-- SHOW JOBS WHERE AVERAGE SALARY GREATER THAN 60000;
